pimcore_data_hub:
    configurations:
        product_category_importer:
            general:
                active: true
                type: dataImporterDataObject
                name: product_category_importer
                description: ''
                group: ''
                path: null
                modificationDate: 1671319491
                createDate: 1671312785
            loaderConfig:
                type: asset
                settings:
                    assetPath: /products.xml
            interpreterConfig:
                type: xml
                settings:
                    xpath: /products/product
                    schema: ''
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: ProductCategoryClass
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: category
                        attributeName: name
                        language: ''
                        includeUnpublished: true
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /imported
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: alwaysPublish
            processingConfig:
                executionType: parallel
                idDataIndex: category
                cleanup:
                    strategy: unpublish
            mappingConfig:
                -
                    label: 'new column'
                    dataSourceIndex:
                        - category
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: name
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'new column'
                    dataSourceIndex:
                        - category
                    settings:
                        search: ' '
                        replace: _
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                search: ' '
                                replace: _
                            type: stringReplace
            executionConfig:
                scheduleType: job
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
