parameters:
    secret: eQ52FtlgMDK+HBqBdX/QX6FvuqnMr/6yi7cuHCStoUE=

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Features\:
        resource: '../src/Features/**'
